"""Generate a PaddleOCR YAML config for Vietnamese invoice recognition finetuning.

We finetune PP-OCRv4 rec (SVTR_LCNet backbone) from the official Vietnamese
pretrained checkpoint — NOT training from scratch. This domain-adapts the model
to invoice-specific fonts, degraded scan quality, and Vietnamese number formats
without requiring millions of labelled images.

Usage:
    # 1. Download pretrained Vietnamese model first:
    #    wget https://paddleocr.bj.bcebos.com/PP-OCRv4/vietnamese/vi_PP-OCRv4_rec_train.tar
    #    tar -xf vi_PP-OCRv4_rec_train.tar -C training/pretrain_models/

    python training/scripts/generate_finetune_config.py \
        --data-dir   training/data/splits \
        --pretrained training/pretrain_models/vi_PP-OCRv4_rec_train/best_accuracy \
        --output-dir training/output/rec_vi_finetune \
        --output     configs/rec_vi_finetune.yml \
        --epochs 20 --lr 0.0001

    # 2. Train:
    python /path/to/PaddleOCR/tools/train.py -c configs/rec_vi_finetune.yml

    # 3. Export checkpoint → inference model:
    python /path/to/PaddleOCR/tools/export_model.py \\
        -c configs/rec_vi_finetune.yml \\
        -o Global.pretrained_model=training/output/rec_vi_finetune/best_accuracy \\
           Global.save_inference_dir=training/output/rec_vi_finetune/inference

    # 4. Push to model registry:
    python training/scripts/push_model.py \\
        --model-type rec \\
        --model-dir  training/output/rec_vi_finetune/inference \\
        --version    v1.x.0 --promote

Finetuning rationale:
    - PP-OCRv4 Vietnamese already covers all Unicode Vietnamese characters
    - Domain gap: generic training data vs scanned invoice images
    - Expected CER improvement: ~30-50% reduction on invoice-specific text
    - Recommended dataset size: ≥500 corrected crops for meaningful improvement;
      ≥2000 for reliable gains; ≥10000 for SOTA-level domain accuracy
"""

from __future__ import annotations

import argparse
from pathlib import Path

import structlog

logger = structlog.get_logger()


# ---------------------------------------------------------------------------
# Config template
# ---------------------------------------------------------------------------

_CONFIG_TEMPLATE = """\
# Auto-generated by generate_finetune_config.py — do NOT edit manually
# Re-run the script to regenerate with updated hyperparameters.

Global:
  use_gpu: {use_gpu}
  epoch_num: {epoch_num}
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: {save_model_dir}
  save_epoch_step: 3
  eval_batch_step: [0, 500]
  cal_metric_during_train: True
  pretrained_model: {pretrained_model}
  checkpoints: null
  save_inference_dir: null
  use_visualdl: False
  character_dict_path: {character_dict_path}
  max_text_length: &max_text_length 100
  infer_mode: False
  use_space_char: True

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: {lr}
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 3.0e-05

Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform:
  Backbone:
    name: PPLCNetV3
    scale: 0.95
  Neck:
    name: SequenceEncoder
    encoder_type: svtr
    dims: 64
    depth: 2
    hidden_dims: 120
    use_guide: True
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 64
            depth: 2
            hidden_dims: 120
            use_guide: True
          Head:
            fc_decay: 0.00001
      - NRTRHead:
          nrtr_dim: 96
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - NRTRLoss:

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False

Train:
  dataset:
    name: SimpleDataSet
    data_dir: {data_dir}
    label_file_list:
      - {train_list}
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - RecConAug:
          prob: 0.5
          epsilon: 0.01
          max_size: 48
          word_information_file: null
      - RecAug:
      - MultiLabelEncode:
          max_text_length: *max_text_length
          character_dict_path: {character_dict_path}
          use_space_char: True
      - RecResizeImg:
          image_shape: [3, 48, 320]
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_gtc
            - length
            - valid_ratio
  loader:
    shuffle: True
    batch_size_per_card: {batch_size}
    drop_last: True
    num_workers: {num_workers}

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: {data_dir}
    label_file_list:
      - {val_list}
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - MultiLabelEncode:
          max_text_length: *max_text_length
          character_dict_path: {character_dict_path}
          use_space_char: True
      - RecResizeImg:
          image_shape: [3, 48, 320]
      - KeepKeys:
          keep_keys:
            - image
            - label_ctc
            - label_gtc
            - length
            - valid_ratio
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: {eval_batch_size}
    num_workers: {num_workers}
"""


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def generate(args: argparse.Namespace) -> Path:
    data_dir = Path(args.data_dir).resolve()
    train_list = data_dir / "train.txt"
    val_list   = data_dir / "val.txt"

    if not train_list.exists():
        raise FileNotFoundError(
            f"{train_list} not found. Run prepare_dataset.py first."
        )
    if not val_list.exists():
        raise FileNotFoundError(
            f"{val_list} not found."
        )

    # Count training samples to set sensible batch size
    with train_list.open(encoding="utf-8") as f:
        train_count = sum(1 for _ in f)
    logger.info("generate_finetune_config.samples", train=train_count)

    # Warn if dataset is too small for meaningful finetuning
    if train_count < 500:
        logger.warning(
            "generate_finetune_config.small_dataset",
            train_count=train_count,
            hint="Aim for ≥500 for meaningful improvement, ≥2000 for reliable gains.",
        )

    use_gpu    = not args.cpu_only
    batch_size = args.batch_size
    eval_batch = min(256, batch_size * 2)

    pretrained = args.pretrained
    if not pretrained:
        pretrained = "training/pretrain_models/vi_PP-OCRv4_rec_train/best_accuracy"
        logger.warning(
            "generate_finetune_config.no_pretrained",
            default=pretrained,
            hint=(
                "Download: wget https://paddleocr.bj.bcebos.com/PP-OCRv4/vietnamese/vi_PP-OCRv4_rec_train.tar"
                " && tar -xf vi_PP-OCRv4_rec_train.tar -C training/pretrain_models/"
            ),
        )

    # character_dict_path is relative to the PaddleOCR repo root (not this project).
    # Pass the absolute path via --char-dict if the PaddleOCR checkout is not on PYTHONPATH.
    char_dict = args.char_dict

    config = _CONFIG_TEMPLATE.format(
        use_gpu=str(use_gpu).lower(),
        epoch_num=args.epochs,
        save_model_dir=args.output_dir,
        pretrained_model=pretrained,
        lr=args.lr,
        data_dir=str(data_dir),
        train_list=str(train_list),
        val_list=str(val_list),
        batch_size=batch_size,
        eval_batch_size=eval_batch,
        num_workers=args.num_workers,
        character_dict_path=char_dict,
    )

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(config, encoding="utf-8")
    logger.info(
        "generate_finetune_config.written",
        path=str(out),
        next_step=f"python /path/to/PaddleOCR/tools/train.py -c {out}",
    )
    return out


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Generate PaddleOCR YAML config for Vietnamese invoice rec finetuning"
    )
    parser.add_argument(
        "--data-dir", required=True,
        help="Directory containing train.txt / val.txt and crops/ (output of prepare_dataset.py)",
    )
    parser.add_argument(
        "--pretrained", default=None,
        help="Path to pretrained vi_PP-OCRv4_rec_train/best_accuracy checkpoint",
    )
    parser.add_argument(
        "--output-dir",
        default="training/output/rec_vi_finetune",
        help="Directory where PaddleOCR saves checkpoints during training",
    )
    parser.add_argument(
        "--output", default="configs/rec_vi_finetune.yml",
        help="Path to write the generated YAML config",
    )
    parser.add_argument("--epochs",      type=int,   default=20)
    parser.add_argument("--lr",          type=float, default=0.0001)
    parser.add_argument("--batch-size",  type=int,   default=128)
    parser.add_argument("--num-workers", type=int,   default=4)
    parser.add_argument(
        "--cpu-only", action="store_true",
        help="Set use_gpu: false (for machines without CUDA)",
    )
    parser.add_argument(
        "--char-dict",
        default="ppocr/utils/dict/vi_dict.txt",
        help=(
            "Path to the Vietnamese character dictionary. "
            "Default 'ppocr/utils/dict/vi_dict.txt' is relative to the PaddleOCR repo root "
            "and works when tools/train.py is run from that directory. "
            "Pass an absolute path if you run train.py from a different working directory."
        ),
    )
    args = parser.parse_args()
    generate(args)
